-- MySQL Script generated by MySQL Workbench
-- Sat 13 Mar 2021 11:00:53 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corona_app_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corona_app_v2` DEFAULT CHARACTER SET utf8 ;
USE `corona_app_v2` ;

CREATE USER corona_app_v2@localhost IDENTIFIED BY 'wfewef';
GRANT ALL PRIVILEGES ON corona_app_v2.* TO corona_app_v2@localhost;

-- -----------------------------------------------------
-- Table `corona_app_v2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corona_app_v2`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

INSERT INTO `corona_app_v2`.`user`(username, password) VALUES('Doctor Doom', '$2y$12$MBbI8A4LOIKWWMcTGTO.8OF1yR82XFF6MllX45X0HrgRRi4RMa06q'); -- 23aw<sef
INSERT INTO `corona_app_v2`.`user`(username, password) VALUES('Bundesgesundheitsamt', '$2y$12$kxj69U.CYPflwGkMoceLlON3IEMys6be1Hl7384m7XF2Zp5/.KV7y'); -- aw2m23llkfjo23

-- -----------------------------------------------------
-- Table `corona_app_v2`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corona_app_v2`.`app_user` (
  `idapp_user` INT NOT NULL AUTO_INCREMENT,
  `health_state` TINYINT NULL DEFAULT 1,
  `change_date` DATETIME NULL,
  PRIMARY KEY (`idapp_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona_app_v2`.`tracking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corona_app_v2`.`tracking` (
  `idtracking` INT NOT NULL AUTO_INCREMENT,
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `sample_time` DATETIME NOT NULL,
  `idapp_user` INT NULL,
  PRIMARY KEY (`idtracking`),
  FOREIGN KEY (`idapp_user`) REFERENCES `corona_app_v2`.`app_user` (`idapp_user`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corona_app_v2`.`group_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corona_app_v2`.`group_list` (
  `idgroup_list` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgroup_list`))
ENGINE = InnoDB;

INSERT INTO `corona_app_v2`.`group_list`(name) VALUES('Doctor');
INSERT INTO `corona_app_v2`.`group_list`(name) VALUES('Health departemtn');

-- -----------------------------------------------------
-- Table `corona_app_v2`.`group_assignement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corona_app_v2`.`group_assignement` (
  `idgroup_assignemnt` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idgroup_list` INT NOT NULL,
  PRIMARY KEY (`idgroup_assignemnt`),
  FOREIGN KEY (`iduser`) REFERENCES `corona_app_v2`.`user` (`iduser`),
  FOREIGN KEY (`idgroup_list`) REFERENCES `corona_app_v2`.`group_list` (`idgroup_list`)
  )
ENGINE = InnoDB;

INSERT INTO `corona_app_v2`.`group_assignement`(iduser, idgroup_list) VALUES(1, 1);
INSERT INTO `corona_app_v2`.`group_assignement`(iduser, idgroup_list) VALUES(2, 2);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
